### PR TITLE
Breadcrumbs section

### LINKED ISSUE #87: Node page breadcrumbs section
image

Very much like the browser back button history, except that this tracks only a continuous chain of associations, and will also not include url hash jumps, and also shows the associations between steps. Navigating to a new node from a search, a url, or some other link on a page will reset the chain. The section will not show when the chain is only one long.

Note the markers to the side. These are not just for show; they indicate the order of flow and that it is a history. Imagine it without them. The directional arrows of the association might create confusion and obfuscate the fact that it is a step-by-step history going forward, even if some of the arrows are pointing up.

This section may be a slight technical challenge (to get an intuitive behavior and the right association details), so we can consider it a stretch goal. But Melissa requested something like this and it should be theoretically doable.

### LINKED ISSUE #111: Node page breadcrumbs section
image

Very much like the browser back button history, except that this tracks only a continuous chain of associations, and will also not include url hash jumps, and also shows the associations between steps. Navigating to a new node from a search, a url, or some other link on a page will reset the chain. The section will not show when the chain is only one long.

Note the markers to the side. These are not just for show; they indicate the order of flow and that it is a history. Imagine it without them. The directional arrows of the association might create confusion and obfuscate the fact that it is a step-by-step history going forward, even if some of the arrows are pointing up.

This section may be a slight technical challenge (to get an intuitive behavior and the right association details), so we can consider it a stretch goal. But Melissa requested something like this and it should be theoretically doable.

### PR DESCRIPTION
**Pull request by vincerubinetti**
closes monarch-initiative/monarch-api#87 

- add mock service worker to git ignore. this file is automatically created when building the app for testing. this allows us to remove the msw exceptions from prettier and eslint.
- update readme
- make new component for linking to node with adding to breadcrumbs
- update flex component
- allow pushing state with link component
- autoselect first option in single select component
- global variable for breadcrumbs list
- conditionally import msw so it doesn't get included in production build
- get rid of set/get route data hack. replace with new vue-router capability to set history state on push/replace
- for popular node searches, only show those that have been searched 3 or more times
- for "send to phenotype explorer" button in text annotator mode, use anchor instead of button and stringify data
- use breadcrumb links for association and evidence tables
- refactor node page association section watchers to fix regression bug (couldn't go backward in browser history stack without erasing forward entries)
- add breadcrumbs section that displays breadcrumbs global variable, with clear button
- json parse/stringify util funcs
- add test for breadcrumbs
- add some customized labels to node page fixture data

### CODE REVIEW

**Review by falquaddoomi — COMMENTED** [review]
Nice! I really like the breadcrumbs feature, so much so that I wonder if it could be moved to a place of more prominence on the page, like  perhaps in the header? No worries if not; it's fine as a section IMO.

I also just noticed that the "popular searches" tooltip references "Shift-Delete" as the hotkey to remove an entry. On my Mac, you have to press the "Fn" key as well to make the key labeled "Delete" (which is actually backspace with no modifiers pressed) do an actual delete. I don't know if that'll be confusing, or if Mac users will just know to press the function key as well. Up to you if you feel like changing it or not; I honestly don't know if it's a real issue.

**Comment by vincerubinetti** [comment]
A little discussion on how this works, because it actually took me a while to figure out.

Before diving into this, I assumed routers would've had a convenience feature of storing an array of the history stack (the list of entries you'd get when right clicking on the browser's back/forward buttons). The browser's built-in history api does not give you this list, as that would be a security issue (imagine being on your bank's website, then going to an app, and that app can tell what bank page you were on). However, when you're navigating on the same domain, your javascript can manually track what pages of your app you've visited. I thought vue-router would do that. It does not.

Why do we need the history stack? Well because that's basically what the breadcrumbs section is, it's showing a richer version of the back button history stack. We want to store the rich metadata about the page we came from -- the node name and the relationship/association -- in each entry. We attach that rich data using the [`state` argument of `pushState`](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState), which basically just makes the browser store and attach some data to a particular history entry.

I thought the approach would be to attach just one thing to each entry -- the previous node -- and then somehow get/track a list of all the previous entries. This is very difficult due to browser limitations. You'd have to account for many scenarios: going back/forward by one or many steps, manually navigating to another page within the same domain, going to an external domain then back again, refreshing the page, etc. This is extremely hacky and tricky; I looked at many different resources and solutions: [1](https://github.com/vuejs/vue-router/issues/953) [2](https://stackoverflow.com/questions/11556781/can-we-get-browser-history-by-using-javascript/11556806#11556806) [3](https://stackoverflow.com/questions/59951828/how-do-i-see-the-navigation-history-in-vue-router/67865426#67865426) (just to name a few).

Luckily I realized a dead simple solution that (I think) covers all of our bases. Instead of keeping just the previous node in the current history entry state, keep the whole running list. When navigating to a new node, simply add that node to the list. Going back one step will just yield the previous list, without the new node. Going back several steps will yield the list at that point in time. Since the browser keeps that data associated with that history entry, the data should be persisted after refreshes and even after going to different domains and back.

**Comment by falquaddoomi** [comment]
Hm, I get your idea of keeping the entire list, and I think that's the right move, but I did notice that the breadcrumbs get wiped if I do a full page refresh. I thought that was by design, but apparently not?

**Comment by vincerubinetti** [comment]
> Nice! I really like the breadcrumbs feature, so much so that I wonder if it could be moved to a place of more prominence on the page, like perhaps in the header? No worries if not; it's fine as a section IMO.

I believe there was some discussion about this, and someone from tislab said to put it at the bottom. But luckily it's extremely easy to change the order of the sections, just in `PageNode.vue`.

> I also just noticed that the "popular searches" tooltip references "Shift-Delete" 

I had a feeling you'd catch and mention this. I struggled with it too. That key is technically mislabeled, as you say. It's really the backspace key, and Fn makes it delete.

I made it shift + del because that's the same hotkey for deleting autofill entries in the chrome address bar. I tried to look up official chrome docs for that hot key just now to see how they describe it for macs, but there are no docs. Not sure what to do here.

**Comment by falquaddoomi** [comment]
> I believe there was some discussion about this, and someone from tislab said to put it at the bottom. But luckily it's extremely easy to change the order of the sections, just in PageNode.vue.

Nice; I suppose we'll see if they decide to move it once they try it out a bit. Good to know it's an easy change.

> I made it shift + del because that's the same hotkey for deleting autofill entries in the chrome address bar. I tried to look up official chrome docs for that hot key just now to see how they describe it for macs, but there are no docs. Not sure what to do here.

It works the same way in Chrome -- it prompts you to press "Shift-Delete", but it requires you to press "Fn" as well for it to actually remove the entry. I think it's fine the way you have it; Mac users will just have to learn that that's how the backspace/delete key works on Macs.

**Comment by vincerubinetti** [comment]
> Hm, I get your idea of keeping the entire list, and I think that's the right move, but I did notice that the breadcrumbs get wiped if I do a full page refresh. I thought that was by design, but apparently not?

It's supposed to keep it. In fact, I'll add that to the e2e test.

Oddly, refreshing the page works when running the app locally, but doesn't seem to work on the netlify preview... I wonder if this is some weird browser permission thing because of the domain... I'll try to debug.

**Comment by falquaddoomi** [comment]
On a side note, I've noticed that navigating around the node pages also affects the suggestions in the search dropdown. I'm fine with it if it's by design, but if not I find it mildly surprising that I'd end up with entries in the list I didn't specifically search for.

**Comment by vincerubinetti** [comment]
> On a side note, I've noticed that navigating around the node pages also affects the suggestions in the search dropdown. I'm fine with it if it's by design, but if not I find it mildly surprising that I'd end up with entries in the list I didn't specifically search for.

Yes that was intentional and is done here:

https://github.com/monarch-initiative/monarch-ui-new/blob/main/src/views/node/PageNode.vue#L113-L115

I thought that if someone was visiting a certain node a lot, even if they hadn't searched for it explicitly, they still might want to see it as a suggestion. I feel like google does similar things maybe.

**Comment by falquaddoomi** [comment]
FWIW, I'm still getting the behavior where the breadcrumbs are preserved on refresh when running the local dev server, but not on Netlify. I also noticed that I don't see the message about a redirect when I refresh on the local version, but I do see it on the Netlify version (presumably because it's hitting `404.html`, where you stuff the prior URL into the session state so you can navigate to it on the homepage if that state exists).

**Comment by vincerubinetti** [comment]
> FWIW, I'm still getting the behavior where the breadcrumbs 

Oh duh, that's gotta be what's causing it. I'll look into modifying that redirect code. Hopefully I can preserve the state that way.

**Comment by vincerubinetti** [comment]
> Personally, it's not a problem for me that the breadcrumbs get wiped if you refresh

Maybe. I've considered this. My feeling atm is that it might be frustrating to accidentally refresh and have all the traversal work lost. We could add a button to manually clear the breadcrumbs if they want to start fresh and can't figure out that you can just open a new tab, manually paste, go to a new node through the search, etc

**Comment by falquaddoomi** [comment]
Not sure about the failed test, but I can verify that your most recent commit to fix the redirects appears to have done the trick -- I see the breadcrumbs preserved on both Chrome on my laptop and on my Android phone.

**Comment by vincerubinetti** [comment]
> Not sure about the failed test, but I can verify that your most recent commit to fix the redirects appears to have done the trick -- I see the breadcrumbs preserved on both Chrome on my laptop and on my Android phone.

Really??? For me, the redirect isn't even working anymore. I think it's because `replaceState` that I changed it to doesn't actually make an HTTP request (to redirect), it just replaces the history entry. If I nav directly to https://deploy-preview-126--monarch-ui-new.netlify.app/about , I just get a white page.

**Comment by falquaddoomi** [comment]
Ah...yeah, I thought that was just my phone being dodgy, but I'm seeing the same behavior on the desktop, too. Might not be a bad idea to implement the suggestion in the vue-router docs for Netlify rather than trying to do it on the 404 page, https://router.vuejs.org/guide/essentials/history-mode.html#netlify. (Generally, I prefer to have all requests go to the index page, then use JS to dispatch to particular pages.)

**Comment by vincerubinetti** [comment]
> Might not be a bad idea to implement the suggestion in the vue-router docs for Netlify 

This would be really nice, but afaik GitHub Pages doesn't support this, so we'd still need the 404.html for that case.

**Comment by vincerubinetti** [comment]
@falquaddoomi Okay I think I've finally squared everything away, check the latest commits.

**Comment by falquaddoomi** [comment]
Nice, seems to be working for me, including the new clear feature you introduced.

**Review by falquaddoomi — APPROVED** [review]

**Pull request merged**
