### PR TITLE
basic node search

### PR DESCRIPTION
**Pull request by vincerubinetti**
- removes types folder and just puts types files near where they are relevant
- use new font awesome 6
- get rid of axios and swagger-typescript-api
- update sitemap
- add category (disease/gene/etc) mapping
- refactor all api files to have a Response and Result types, and to not use swagger-typescript-api
- axios is heavy, not actively maintained, and now unnecessary. replace with custom request function.
- add custom ApiError that integrates nicely with status component
- implement node search from biolink with search, filters, boost-q's, etc
- add taxon map
- remove swagger-typescript-api. it was a nice idea, but i ran into too many problems. 1) the type definitions from biolink in many/most cases are not well defined enough to be useful to me anyway, and 2) the fetch/http client that the package generates lacks documentation and does things in a different format than the standard fetch. i may go back to using this package in the future, but i'd only use the generated types and not the client.
- import, format, and clean category svg icons
- refactor button component again and add click-to-copy option
- add inline-svg package to inline svgs for use of currentColor and etc
- flesh out input component
- add optional chaining before use of document, because of testing
- sync tab component with url hash
- make float buttons also update on dom mutation
- get rid of "custom icons" being vue components, and do it via inlining svgs
- add a flag to mock api responses when developing locally
- add placeholder node page and routes
- add more information to tab title, like hash, search, etc
- clean up testbed
- add basic tabs and node search to explore page and home page. when on home page, immediately nav to explore when focusing text box or switching tabs.
- add node search with real api, results, filters, pagination, and example queries
- write tests for node search

### CODE REVIEW

**Comment by vincerubinetti** [comment]
Answers to the above two questions:

- For now, I'm just going to take the categories as they come from biolink. Since it's an array, I'm just going to take the first entry. No mapping at all. We can create an issue later if someone believes how the categories are handled is wrong

- I created https://github.com/biolink/biolink-api/issues/386 to ask for the biolink api to just return the info I need. But since that likely wont get implemented for a while, I'm going to keep the ugly taxon map, otherwise taxon filtering just wont work at all.

**Comment by vincerubinetti** [comment]
@putmantime One last question for this PR, do you have any opposition to me adding `"boost_q=category:gene^-10` to this list: https://github.com/monarch-initiative/monarch-ui/blob/master/src/api/bio-link.js#L435-L439 

Since it seems like we want genes to also be prioritized in results.

**Comment by putmantime** [comment]
> @putmantime One last question for this PR, do you have any opposition to me adding `boost_q=category:gene^-10` to this list: https://github.com/monarch-initiative/monarch-ui/blob/master/src/api/bio-link.js#L435-L439
> 
> Since it seems like we want genes to also be prioritized in results.

That does seem wrong that genes is not in that list.
I would certainly add it.

**Review by falquaddoomi — APPROVED** [review]
Seems to me like it's working well since the commit where the taxon ID mapping was added back in. Once I have some time, I'll try to address the biolink API issue you brought up, i.e. to inline the taxon IDs into the response along with the labels.

**Comment by vincerubinetti** [comment]
@putmantime how's the UI behavior and look (overall. we can take a closer look later).

**Review by putmantime — APPROVED** [review]

**Pull request merged**
