### PR TITLE
Node page overview and details sections

### PR DESCRIPTION
**Pull request by vincerubinetti**
Addresses monarch-initiative/monarch-api#122 (technically closes, but i'll wait until we discuss it in person).

- add explanatory comments to public/404.html
- incorporate json linked-data spec into public index.html. in 2.0, this is done with a data string in the Node.vue component. doing it in index.html is cleaner. also it seems that the spec is a website-global thing, like a sitemap almost, and i dont believe it matters if we have it on every page instead of just the node page
- update sitemap
- make simplified mapCategory func instead of hard-coding it in place
- add text parse option to request func
- use console.error exactly in api error, just to get more stack trace info. still keep it in a collapse log group to distinguish between uncaught errors
- add api code to look up gene metadata from mygene
- add api code to get node hierarchy data, simplified from 2.0 code and tracked in monarch-initiative/monarch-api#119 
- reorganize node lookup api code, and incorp gene and publication metadata
- add api code to look up publication metadata from entrez
- change some variable names to make things more consistent. `value` -> `id`, `label` -> `name`
- refactor types in phenotype explorer api code a bit
- import external references map from UI 2.0. simplified/ignored code from 2.0 and tracked in monarch-initiative/monarch-api#118 
- create new "detail" component for showing fields on node page
- remove "fallback" option from app icon, as it was only used for category. write the category fallback icon just once, in the icon component
- separate the "unknown" (blank or unmappable) category icon from the "fallback" (valid but we dont have an icon design for it) category icon
- narrow multi/tag select types
- make tags select component more robust. dedupe values, and fix some test issues
- put app version hidden in the logo (for future debugging)
- tweak table of contents component
- rearrange router file. label routes better. get rid of conditional testbed (i want to be able to see it in live too, we'll remove it later). reorder. add "NodeRaw" route match. make 404 redirecting a little clearer.
- add temporary way to pass arbitrary data on router push
- add better pagination controls for node search results. instead of showing whole list of pages (which can get massive), only show first few, last few, and middle few (+/- the current page)
- split + separated lists in phenotype explorer results into separate links per-phenotype. also tweak "top X" heading message.
- when passing phenotypes from text annotator to phenotype explorer, pass the `name` too, not just the `id`, using the aforementioned "pass arbitrary data on router push" feature
- fill out overview/details/hierarchy (more)
- add note to node page when biolink redirects us to a different ID (dont know why this is a thing that can happen, but at least the user will know about it now)
- write e2e tests for node page content
- add test fixture data and msw mocks for the above-mentioned new api code
- tweak test setup.ts util emitted func

### CODE REVIEW

**Review by falquaddoomi — COMMENTED** [review]
It's coming along nicely, although I noticed a few things:
1. Opening a link in a new tab/window (e.g., via command-clicking) appears to go back to the homepage, whereas navigating to the link in-page loads it normally. For example, https://deploy-preview-94--monarch-ui-new.netlify.app/phenotype/HP:0001903 just takes me to the homepage, but searching for "anemia" and clicking that in-page shows the page correctly.
2. On the text annotator page, all the tooltip links in the body are broken, presumably b/c they belong to the "unknown" category?
3. IMHO it'd be nice to see the identifiers in the "Top 10 matches" list; if someone else has already commented on that, then disregard this.
4. It's cool to see the version number, although I don't find it particularly hidden as a tooltip on the header image. Perhaps it could be put in the footer before the license, e.g. "Monarch Intiative 2022  · v0.1.0 · [BSD-3]"?
5. On the node page, Details section: under IRI, I'm personally not a big fan of links being labeled "Link". Perhaps you could put something in it to indicate where it goes, or maybe just the ID again...?
6. On the node page, Hierarchy section: I don't think it's necessary to quote "parent", "sibling", and "children" in the tooltips -- those are well-known terms for tree relationships AFAIK.

**Comment by vincerubinetti** [comment]
1. this seems to be an issue with the 404 redirection. it doesn't seem to happen when testing locally, so i'll try making some commits and see if it works on the netlify preview

2. yes, that is related to this issue https://github.com/biolink/biolink-api/issues/387 i wont be able to link to the node page until i have the correct category info returned from the backend. unless i link to all of the nodes without the category (which does a lookup to determine the category).

3. i can add this

4. i assume you meant "i don't find it particularly useful, hidden as a tooltip". the use case for this version number is very limited, which is why i buried it there. in the past, i've done this just to make sure there are no caching issues with my browser or with github pages; basically to quickly see that i'm on the latest version. the usefulness to the average user will be very limited, because everyone should always get the latest version of the app by default. the only use i could see for it is as a way to notify people that something about the app has changed since the last time they visited (and there are better ways to indicate that than a version string). i'm also not certain yet how disciplined we're going to be about updating the version number; i haven't changed it yet.

5. i can add that

6. someone explained the super/sub classes to me once, and my understanding of them was that it's not *exactly* like a hierarchy. regardless, i'd just ignore this for now because tislab will no doubt pour over every word of explanatory text in this app at the end (all tooltips, paragraphs before sections, etc).

**Comment by falquaddoomi** [comment]
Sounds good, although I did mean that the version number didn't seem hidden for me -- I immediately noticed it when mousing around the page. If it's just for debugging for now then it's fine, of course, and I agree that a version number is of limited usefulness when everyone's (hopefully) getting the latest version.

**Comment by vincerubinetti** [comment]
Oh you saw it pretty easily? On most browsers it usually takes a good full 1-2 seconds for a `title` attribute to pop up. What browser? This might be a selection bias thing too, as you're probably hovering over things longer while poking around than most users would.

Also for 5, I just took the IRI url and took everything after the last `/`. I did this rather than repeating the id just in case they're different in some way (I've certainly come across exceptions like this before).

**Comment by falquaddoomi** [comment]
Never mind, you're right, it's 1-2 seconds...in any case, I'm on Chrome 99.0.4844.83 on OS X 12.2.1. IRI looks good now, too.

Regarding the 404s, it occurred to me that it's likely an issue of Netlify handling 404s on its own rather than letting the client deal with them. There's a quick fix here: https://answers.netlify.com/t/support-guide-direct-links-to-my-single-page-app-spa-dont-work/126 and more information here: https://docs.netlify.com/routing/redirects/rewrites-proxies/#history-pushstate-and-single-page-apps. Ideally your router should send back a 404-like page, but unfortunately AFAIK client-side code can't change the status code (since the browser's already fetched it). Outside of a meta redirect or some kind of handling in the proxy once we get this in production, a 200 response with a 404-looking page is the best we can do, I think.

**Comment by vincerubinetti** [comment]
No worries regarding the 404. This was working before and I realized what broke it. Check my latest commit.

**Review by falquaddoomi — APPROVED** [review]

**Comment by vincerubinetti** [comment]
Is it my imagination or did the diff line count just jump from like 1000 to 8000. Or was it always 8000.

There's a lot of changes, including big fixture json files, but that still seems like a lot. Did I add a wrong file.

**Comment by falquaddoomi** [comment]
I think it's been at ~8,000 since you submitted it for review to me. Looks like the majority of that is coming from [tests/fixtures/node-hierarchy.json](https://github.com/monarch-initiative/monarch-ui-new/pull/94/files#diff-d0ded05bdd92d70dd28125d29ed70f8995f5bad096db6e958e49096ee6d9348d),

**Comment by vincerubinetti** [comment]
Nvm the node-hierarchy.json fixture file is the culprit. I'm gonna prune that down a little bit.

**Pull request merged**
