### PR TITLE
Floating ui

### LINKED ISSUE #96: Offload accessibility and positioning burden of select components to 3rd party libraries
Right now, I'm using vue-tippy for tooltip position, accessibility, and styling. But for multi select components, which also have dropdowns/popovers, I'm doing all of that manually. With positioning, I'm doing it very simply, with no sliding/flipping/etc when the dropdown goes beyond the screen.

Two main libraries to look at:

- the brand new and cleanly refactored [floating ui](https://floating-ui.com/docs/react-dom-interactions). used for correctly positioning tooltips/popovers/menus/etc. might also be usable for accessibility in the future, if they ever make a Vue version of their [`use` React hooks](https://floating-ui.com/docs/useListNavigation). might also be used to replace my custom modal code as well.
- [vue combo blocks](https://github.com/sssmi/vue-combo-blocks), a Vue version of the React library [downshift](https://www.downshift-js.com/use-combobox) which has a very convenient and clean way to get all the accessibility props you need for a select component. it doesn't have many users at the moment, but there must be an alternative. and as stated above, hopefully floating ui will implement this soon, so we only need one library for all of this.

### LINKED ISSUE #98: Offload accessibility and positioning burden of select components to 3rd party libraries
Right now, I'm using vue-tippy for tooltip position, accessibility, and styling. But for multi select components, which also have dropdowns/popovers, I'm doing all of that manually. With positioning, I'm doing it very simply, with no sliding/flipping/etc when the dropdown goes beyond the screen.

Two main libraries to look at:

- the brand new and cleanly refactored [floating ui](https://floating-ui.com/docs/react-dom-interactions). used for correctly positioning tooltips/popovers/menus/etc. might also be usable for accessibility in the future, if they ever make a Vue version of their [`use` React hooks](https://floating-ui.com/docs/useListNavigation). might also be used to replace my custom modal code as well.
- [vue combo blocks](https://github.com/sssmi/vue-combo-blocks), a Vue version of the React library [downshift](https://www.downshift-js.com/use-combobox) which has a very convenient and clean way to get all the accessibility props you need for a select component. it doesn't have many users at the moment, but there must be an alternative. and as stated above, hopefully floating ui will implement this soon, so we only need one library for all of this.

### PR DESCRIPTION
**Pull request by vincerubinetti**
closes monarch-initiative/monarch-api#96  (positioning burden lifted, accessibility burden not. no acceptable libraries found at this time to lift that burden.)

- rename v-tippy to v-tooltip. better clarity, library-agnostic, positions us better to switch off of tippy in future
- install floating ui for pure positioning of dropdowns/popups/etc. this is already a part of tippy, but they don't expose just the positioning engine without any styling. when floating ui is more mature and has associated libraries for accessible tooltips, hopefully we will switch tippy to floating-ui too.
- make little red notification dot into generic class
- use floating ui to position select component dropdowns, and update components a bit
- make useFloating composable to allow components to be positioned with floating ui
- get rid of kebabify util func, no longer needed due to some component refactors
- add testbed to axe test, and open up each select component to check for accessibility issues with dropdown

### CODE REVIEW

**Review by falquaddoomi — COMMENTED** [review]
Nice work! One very minor cosmetic thing I noticed is that the floating dropdowns will remain in place (i.e., they'll become detached from their parent element) if the window is resized. I'll leave it up to you whether that's worth fixing.

If you do decide to fix it, you could handle add an event listener for the window `resize` event and call your `calculate` method whenever it triggers (possibly debouncing it if there are performance issues, but I didn't notice any when I tried it).

**Comment by vincerubinetti** [comment]
@falquaddoomi Where did you notice this. All of the select components should close when losing focus (which you'd need to do to resize the window).

I also think it'd be pretty rare for a user to resize a window while having a dropdown open. Instead I'd probably add a scroll listener in `useFloating`. It might be more common for a user to scroll up and down while a dropdown is open.

**Comment by falquaddoomi** [comment]
> @falquaddoomi Where did you notice this. All of the select components should close when losing focus (which you'd need to do to resize the window).

The select components do close when they lose focus, but resizing the window (at least in Chrome on OS X) doesn't cause a change in focus. Also, scrolling works fine. I've attached a video of the behavior here:

https://user-images.githubusercontent.com/312923/181814377-40567772-d928-4df5-9c2a-1ee1140ef27a.mov

(Again, this is an extremely minor cosmetic "issue" that might not even  be an issue. No worries if you'd rather leave it as-is.)

**Comment by vincerubinetti** [comment]
Ah okay I hadn't tried resizing the window in that way, weird that it doesn't blur the focused element. I'll add it. Also re: scrolling I was just referring to it properly flipping sides.

**Comment by vincerubinetti** [comment]
Here's the commit from the next PR that implements this fix:

https://github.com/monarch-initiative/monarch-ui-new/commit/ae5c04511407ca8e94de1b8de1bdd481c95823c1

**Comment by falquaddoomi** [comment]
Nice, that commit looks better than what I would've done. Kudos!

**Review by falquaddoomi — APPROVED** [review]

**Pull request merged**
