### PR TITLE
Multiselect tags component

### PR DESCRIPTION
**Pull request by vincerubinetti**
- make checkmarks make use of icon component svgs instead of CSS backgrounds (a little more visually consistent)
- undo pattern where i separate long functions from the component definitions, e.g. `this: InstanceType<typeof Heading>` and `getTag.call(this)` †
- build debounce right into primitive components like input, and dispatch change event when user has submitted or debounce has completed
- make multi select component only "change" when closed (instead of debounce) ††
- add new tags multi-select component with tests and testbed
- refactor/simplify node search debounce stuff to just use primitive component built-in debounces and such
- refactor test setup functions. mock lodash debounce to execute immediately. create generic standard mounting function.

† originally i think i did this because i wanted to keep long functions separated from the rest of the component. but that quickly went out of the window and i stopped doing it, so i reverted the original few times i did it. that pattern also arguably is just uglier anyway. another reason i may have done it in certain places it to debounce functions, but i found a [better pattern for that](https://forum.vuejs.org/t/how-to-get-typescript-method-callback-working/36825/7?u=vincerubinetti)

†† this first pass at a tags component doesn't include one functionality i'll eventually need: the user needs to be able to do a fuzzy search for a phenotype (this component is really only going to be used for the phenotype explorer), which this supports. but the user also needs to be able to paste a comma-separated list of exact phenotype ids and the component needs to auto-accept/select those as the values. my plan for this is to just have the `options` prop, which is currently takes the form `(value: string) => Promise<Options>`, also accept a flag that says "automatically accept this array of options, don't show them to let the user click-to-select". it'll be something like `(value: string) => Promise<{autoAccept: boolean, options: Options}>`

### CODE REVIEW

**Comment by vincerubinetti** [comment]
Yeah you're right, that is normally how other components like this work. The only reason I didn't do that here is because I thought maybe there would be cases of "whoops i accidentally clicked to select the wrong element", and it's easier to just click again in place than find the last entry in the above list.

But I'll just go with standard behavior. If someone complains about that, I can come back and add the checkboxes. Not hard to add back in.

**Comment by vincerubinetti** [comment]
@falquaddoomi updated

**Comment by falquaddoomi** [comment]
Hm, maybe I'm misunderstanding what you suggested, but the behavior I'm seeing now is that the query text doesn't get cleared when you select something, but it does when the box is defocused. Also, the options now appear when the box is defocused -- I don't recall if it was like that before, but that seems odd to me, too.

**Comment by vincerubinetti** [comment]
Good catch. That would've been a bug before the previous commit as well, and only under certain circumstances. The most recent commit should fix both those.

**Review by falquaddoomi — APPROVED** [review]
Seems like it's working now. Nice work!

**Pull request merged**
