### PR TITLE
Evidence viewer

### PR DESCRIPTION
**Pull request by vincerubinetti**
- upgrade font awesome for some new icons
- add association evidence api code
- refactor association type
- where possible, don't permanently change case of names/ids/etc in case we need to give them back to biolink, instead rely on css text transform, or in-situ case transforming where possible
- add "hp" to xrefs? i just noticed this and threw it in there, but xrefs as a whole needs a complete re-look/re-working, per monarch-initiative/monarch-api#118 
- rename vague "push" function to "snackbar"
- add icon and count option to detail component for node page
- comment out built-in auto-select in single select component. handle outside component instead, ie association category select
- add temporary option to hide table controls for when no server-side pagination/search/etc available
- fix up `useScroll` in table component a little. still not perfect, but this is an upstream issue
- add option to table component to expand to full screen width
- pull description prop out of tabs component and just put it as plain text in pages
- add dashed underline to plain text that has tooltip
- refactor router "jump" functions
- update some util funcs
- add basic, MVP evidence viewer component, with summary and table view
- convert hierarchy section on node page to just use detail component like everything else
- add fixture data and tests associated with new evidence viewer

### CODE REVIEW

**Comment by falquaddoomi** [comment]
Just FYI, I'd noticed that the "Evidence summary viewer works" test had failed (in the file [tests/e2e/specs/node.js](https://github.com/monarch-initiative/monarch-ui-new/pull/108/files#diff-79183909a5852542a11dab9a445f78b1bca4b05a977784ab116957d940ff439f)), but I couldn't find a reason why. I re-ran the test suite and it passed.

**Review by falquaddoomi — COMMENTED** [review]
It all looks pretty good to me! One minor thing, and I'm not sure if this is a browser issue or not, but the dashed underline and boldface on "And X more..." seems a bit strong to me. Perhaps a dotted line (rather than dashed), with a little margin between the line and text, would be more subtle?
Screen Shot 2022-04-14 at 8 59 14 PM

**Review by putmantime — APPROVED** [review]
Looks really nice @vincerubinetti .
I agree with @falquaddoomi that dashed underline could be a little easier on the eyes.
Other than that I think we are in good shape.  Lets reconvene early next week to talk about next steps

**Comment by vincerubinetti** [comment]
> It all looks pretty good to me! One minor thing, and I'm not sure if this is a browser issue or not, but the dashed underline and boldface on "And X more..." seems a bit strong to me. Perhaps a dotted line (rather than dashed), with a little margin between the line and text, would be more subtle? Screen Shot 2022-04-14 at 8 59 14 PM

I think this is one of those things that will look slightly different on all platforms and browsers. E.g. here's chrome vs firefox on windows:

image
image

Never the less I made it dotted and increased the offset. It may end up looking awkwardly far on some browsers, but it at least looks better on the browsers I use.

**Comment by vincerubinetti** [comment]
> Just FYI, I'd noticed that the "Evidence summary viewer works" test had failed

I believe I fixed this with my latest commit. How I had the test written before made it sensitive to the timing of the evidence api call returning. Now it should wait for a long time (the cypress default is 4 sec I think) trying to find the next DOM element to proceed with the test.

**Pull request merged**
