### PR TITLE
Phenotype explorer extras

### LINKED ISSUE #86: Additional phenotype explorer features
#83 implements most of the phenotype explorer features I wanted, but there still remain a few minor things.

- a warning (probably using the snack bar component) when you've pasted phenotype ids that are not valid HPO ids
- "generated from" helper text, per the figma sketch, e.g. you search and select "marfan syndrome" and it populates 12 phenotypes or whatever, text appears that says "generated from marfan syndrome", until the user makes any modifications to the selected phenotypes
- ~when pasting raw ids, i'm not doing any queries to get additional metadata, like the label (which the 2.0 UI does do). i'm not sure if this is really necessary, because i'm thinking that if a user already has raw phenotype IDs, they already know what the list represents. in fact, since i'm only showing one piece of information per selected item to save space (the label, or otherwise the id), maybe that one piece *should* be the pasted id so the user can see exactly what they pasted, and not convert them into human labels.~ i'm not going to do this until someone requests it.
- have button to send text annotator results to phenotype explorer

### LINKED ISSUE #125: Additional phenotype explorer features
monarch-initiative/monarch-ui-new#83 implements most of the phenotype explorer features I wanted, but there still remain a few minor things.

- a warning (probably using the snack bar component) when you've pasted phenotype ids that are not valid HPO ids
- "generated from" helper text, per the figma sketch, e.g. you search and select "marfan syndrome" and it populates 12 phenotypes or whatever, text appears that says "generated from marfan syndrome", until the user makes any modifications to the selected phenotypes
- ~when pasting raw ids, i'm not doing any queries to get additional metadata, like the label (which the 2.0 UI does do). i'm not sure if this is really necessary, because i'm thinking that if a user already has raw phenotype IDs, they already know what the list represents. in fact, since i'm only showing one piece of information per selected item to save space (the label, or otherwise the id), maybe that one piece *should* be the pasted id so the user can see exactly what they pasted, and not convert them into human labels.~ i'm not going to do this until someone requests it.
- have button to send text annotator results to phenotype explorer

### PR DESCRIPTION
**Pull request by vincerubinetti**
Closes monarch-initiative/monarch-api#125  and addresses some comments in monarch-initiative/monarch-ui-new#83 review

- install phenogrid (and incorrectly missing peer dependency file-saver)
- make wrapper component for phenogrid
- copy phenogrid css bundle and attempt to fix a few things (but overall needs to be completely re-written)
- adds warning when non-HPO: prefixed ids are pasted
- rename tag select valueFunc property to more intuitive getOptions and refactor how it works a bit
- update taxon hard-coded map in phenotype explorer api code
- switch to await nextTick instead of call back (cleaner)
- add description prop to tags select component that is for showing metadata beneath the box
- add appropriate aria attributes to snackbar component
- add flashing to snackbar component for repeated clicks while it's still open
- add typescript shim for phenogrid
- add some util funcs to support the above
- add "generated from" message to phenotype explorer that gets set when you select a gene/disease and get several phenotypes in return, and gets unset when the user makes a modification to the selected phenotypes (that is, the message only displays if the selected phenotypes exactly match the phenotypes of the last-selected gene/disease)
- incorporate phenogrid into phenotype explorer view
- add "send to phenotype explorer" button to text annotator results

### CODE REVIEW

**Comment by falquaddoomi** [comment]
I'm seeing some funny behavior from the netlify version: on the Phenotype Explorer page, if I select "try an example", then press "analyze", the phenogrid widget is perpetually in a loading state and I see the following (abbreviated) stack trace in the console:

```
phenogrid.ts:68 TypeError: item.includes is not a function
    at eval (webpack:///./node_modules/phenogrid/js/dataloader.js?:42:17)
    at Array.filter (<anonymous>)
    at buildCompareQuery (webpack:///./node_modules/phenogrid/js/dataloader.js?:41:38)
    at DataLoader.loadCompareData (webpack:///./node_modules/phenogrid/js/dataloader.js?:169:19)
    at $.<computed>.<computed>._initCompare (webpack:///./node_modules/phenogrid/js/phenogrid.js?:380:35)
    at $.<computed>.<computed>.eval [as _initCompare] (webpack:///./node_modules/jquery-ui/ui/widget.js?:131:25)
    at $.<computed>.<computed>._create (webpack:///./node_modules/phenogrid/js/phenogrid.js?:319:30)
    at $.<computed>.<computed>.eval [as _create] (webpack:///./node_modules/jquery-ui/ui/widget.js?:131:25)
    at $.<computed>.<computed>._createWidget (webpack:///./node_modules/jquery-ui/ui/widget.js?:328:8)
    at new $.<computed>.<computed> (webpack:///./node_modules/jquery-ui/ui/widget.js?:86:9)
...
```

The source of the exception appears to be https://github.com/monarch-initiative/phenogrid/blob/master/js/dataloader.js#L42, because  `compareList` (seemingly copied from the `geneList` option) is an array of objects, each of which doesn't have a method `includes()`. I assume `buildCompareQuery()` is expecting an array of strings for `compareList`, and in fact I can't find anywhere where `geneList` is specified at all, let alone as an array of objects matching `xAxis`. I've noticed that in your `mountPhenogrid()` method, `geneList` is set to the same value as `xAxis` -- how did you decide to set it like that? I ask out of honest curiosity; I see no guidance for how `geneList` should be set in the phenogrid docs or source code.

A possible quick fix: in the call to `Phenogrid.createPhenogridForElement()`, you could change the `geneList` initialization to `geneList: xAxis.map((x) => [x.groupId])` and update its type to `Array<Array<string>>`. I'm not sure if that makes sense on a high level (I'm still not familiar with how Phenogrid is supposed to work), but the component displays, at least.

**Review by falquaddoomi — COMMENTED** [review]
The snackbar timeout seems long enough now, and I like the extra usability bits, like the flashing text color when another message appears. The text annotator -> phenotype explorer integration works. It's really cool to see it in action complete with Phenogrid at the bottom.

I do wonder about the warning when pasting a non-HPO identifier...I get why you chose to display it as a snackbar message (do you call those toasts?), but I think it might work better as a validation message underneath the text box, unless it really is supposed to occur as a reaction to the pasting event and not a general warning about the contents of the text box.

Other than that, and the one issue I mentioned with the example query on the Phenotype Explorer page, it all looks good!

**Comment by vincerubinetti** [comment]
> unless it really is supposed to occur as a reaction to the pasting event and not a general warning about the contents of the text box.

This is what it comes down to. The snack bar shouldn't really be used for anything permanent, just for transient, repetitive, or less important things.

The thing is, in UI 2.0, they seem to warn about valid HPO ids only when you do the "paste ids" workflow, which is why I triggered the warning just for paste here.

If the similarity endpoints and/or phenogrid can't handle anything but `HP:` ids, then I agree it should be a general warning. But that doesn't seem to be how they considered things in 2.0.

And also I don't really understand why the phenotypes are supposed to be limited to `HP:`, since searching for genes can yield different identifier types, like `FBcv:`, and just searching for phenotypes manually yields a lot of non-`HP:` ids:

image

**Review by falquaddoomi — APPROVED** [review]
Agreed w/your comment about matching 2.0, and it seems the geneList issue is fixed, so I think it's all good to go.

**Comment by vincerubinetti** [comment]
>I've noticed that in your mountPhenogrid() method, geneList is set to the same value as xAxis -- how did you decide to set it like that?

[This line of code in 2.0](https://github.com/monarch-initiative/monarch-ui/blob/master/src/components/PhenoGrid.vue#L65).

I've updated the type and `geneList` input param as you suggested, but really this is a problem that should be documented in phenogrid.

If I remove the `geneList` param completely, we get a different error. It's really bad that the `geneList` parameter is not documented anywhere, as you say, but is essential for it to work.

**Comment by falquaddoomi** [comment]
Agreed, that's an issue that should be documented...super weird that it works in 2.0, since as far as I can tell that's exactly what you had. Git blame informs me that that line was contributed by Mike Gargano, so perhaps he's someone we could ask about it?

**Comment by vincerubinetti** [comment]
By shimming `Phenogrid.createPhenogridForElement` in 2.0, I get these arguments passed to it:

```json
{
    "serverURL": "https://api-gcp.monarchinitiative.org/api/",
    "forceBiolink": true,
    "appURL": "https://monarchinitiative.org",
    "gridSkeletonData": {
        "title": "Phenogrid Results",
        "xAxis": [
            [
                "HP:0002650"
            ],
            [
                "HP:0004872"
            ],
            [
                "HP:0012499"
            ]
        ],
        "yAxis": [
            {
                "id": "HP:0004933",
                "term": "Ascending aortic dissection"
            },
            {
                "id": "HP:0004970",
                "term": "Ascending tubular aorta aneurysm"
            },
            {
                "id": "HP:0004927",
                "term": "Pulmonary artery dilatation"
            }
        ]
    },
    "selectedCalculation": 0,
    "selectedSort": "Frequency",
    "geneList": [
        [
            "HP:0002650"
        ],
        [
            "HP:0004872"
        ],
        [
            "HP:0012499"
        ]
    ],
    "owlSimFunction": "compare"
}
```

I didn't catch that they were wrapping the id in another array [here](https://github.com/monarch-initiative/monarch-ui/blob/59d43400eeefd9e5e31c593fb96d3d9ef657e046/src/views/AnalyzePhenotypes.vue#L844). I just assumed they would be following what the Phenogrid documentation says it accepts for the xaxis...

Also looking at the phenogrid code, it seems to want just a plain `Array<string>` for `geneList`/`compareList`.... but perhaps I am missing something.

None of this makes any sense, but at least with that last commit we are conforming to 2.0.

**Comment by vincerubinetti** [comment]
Actually, just to make sure we're following 2.0 to the letter, I made another commit. Please take a look and then I'll finally merge.

If you look at [these lines](https://github.com/monarch-initiative/monarch-ui/blob/59d43400eeefd9e5e31c593fb96d3d9ef657e046/src/views/AnalyzePhenotypes.vue#L830-L856) in 2.0, they're only doing that `(x) => [x.groupId]` when the mode is `compare`, i.e. phenotype set vs phenotype set, but leaving it as a `{groupId, groupName}` object when mode is `search`, i.e. phenotype set vs gene/disease.

**Pull request merged**
