### PR TITLE
Pull dataset sources from biolink and add automatic typescript types and api client from biolink

### PR DESCRIPTION
**Pull request by vincerubinetti**
- add package which generates typescript definitions and api client automatically from biolink swagger json schema
- construct function which returns the same results as the more convoluted UI 2.0 method
- move static source data into api folder, and make generic merge util function for it
- add status to source page

Compare this code (all in `src/api/datasets.ts`) to the code in:
https://github.com/monarch-initiative/monarch-ui/blob/master/src/api/bbop-graph-util.js
https://github.com/monarch-initiative/monarch-ui/blob/master/src/api/static-source-data.js
https://github.com/monarch-initiative/monarch-ui/blob/master/src/api/bio-link.js (`getSources`)

And compare content (with just datasets selected) to the content on:
https://monarchinitiative.org/about/data-sources

Please review this closely and carefully. I believe I've done this in an equivalent way to UI 2.0. It seems to return all the same results, but without having to install the `bbopgraph` package and do a bunch of circuitous data manipulation (like in `bbop-graph-util.js`).

I'm still in the process of writing a test for the sources page.

### CODE REVIEW

**Comment by falquaddoomi** [comment]
Some things I noticed just comparing the data source pages side-by-side:
- ClinVar seems to be missing from 3.0
- Not a big deal, but the order is slightly different between 3.0 and 2.0 (e.g., "Gene expression data in animals" appears in a different spot, "GWAS Catalog" and "Gene Ontology Database" are swapped, etc.)
- There's a weird "MonarchArchive:202103/#mgislim" entry that appears in 2.0 that's not in 3.0.
- "Monochrom" has the Monarch logo in 2.0, no logo in 3.0.
- "Mouse Genome Informatics (MGI Slim)" appears in 2.0, but not in 3.0.
- "MyChem" appears in 2.0, but not 3.0.
- "Retrieved on" annotations for individual files in 2.0, but not in 3.0:
  * "National Center for Biotechnology Information" in 2.0 has a "retrieved on 2021-03-10" annotation on one file, but not in 3.0.
  * "Online Mendelian Inheritance in Man" has three such annotations
  * "PANTHER" has one annotation
  * "UCSC Bands" has many annotations, one per file (which all match the "retrieved on "date, so that's weird...)
  * "WormBase database of nematode biology" has one annotation
  * "Zebrafish Information Network" has two annotations
- "PANTHER" in 2.0 has a directory link that appears as an empty link in 3.0.
- "Undiagnosed Diseases Program (UDP)" appears in 2.0, but not in 3.0.
- "Zebrafish Information Network" has a weird "0.0.0.0" entry in both 2.0 and 3.0.
- "Zebrafish Information Network" has a link to [id_map_zfin.tsv](http://purl.obolibrary.org/obo/zp//id_map_zfin.tsv) that's broken in both versions due to the double slash after `zp`. Changing it to a single slash fixes the link.

A minor note: I like how tidy the filenames look in 3.0, but the full URL is useful to figure out, e.g., in "UCSC Bands" which filename corresponds to which gene assembly. It'd be nice if there were an option to show them on hover-over.

**Comment by vincerubinetti** [comment]
> * "ClinVar" appears in 2.0, but not in 3.0.

Fixed

> * Not a big deal, but the order is slightly different between 3.0 and 2.0 (e.g., "Gene expression data in animals" appears in a different spot, "GWAS Catalog" and "Gene Ontology Database" are swapped, etc.)

I'm just sorting them alphabetically case insensitively, and 2.0 was sorting case-sensitively.

> * There's a weird "MonarchArchive:202103/#mgislim" entry that appears in 2.0 that's not in 3.0.

Fixed. Now in 3.0, but clearly there's data missing here that should be added to 3.0 under `src/api/datasets.json`. @putmantime ? @kevinschaper?

> * "Monochrom" has the Monarch logo in 2.0, no logo in 3.0.

Good catch. That image was missing from `/src/assets/sources`. I also went through `/src/api/datasets.json` and make sure all the images were there.

> * "Mouse Genome Informatics (MGI Slim)" appears in 2.0, but not in 3.0.

Fixed.

> * "MyChem" appears in 2.0, but not 3.0.

Fixed.

> * "Retrieved on" annotations for individual files in 2.0, but not in 3.0:
>   * "National Center for Biotechnology Information" in 2.0 has a "retrieved on 2021-03-10" annotation on one file, but not in 3.0.
>   * "Online Mendelian Inheritance in Man" has three such annotations
>   * "PANTHER" has one annotation
>   * "UCSC Bands" has many annotations, one per file (which all match the "retrieved on "date, so that's weird...)
>   * "WormBase database of nematode biology" has one annotation
>   * "Zebrafish Information Network" has two annotations

This was an intentional omission. @putmantime is this important.

> * "PANTHER" in 2.0 has a directory link that appears as a link with an empty title in 3.0.

Will fix.

> * "Undiagnosed Diseases Program (UDP)" appears in 2.0, but not in 3.0.

Fixed.

> * "Zebrafish Information Network" has a weird "0.0.0.0" entry in both 2.0 and 3.0.
> * "Zebrafish Information Network" has a link to [id_map_zfin.tsv](http://purl.obolibrary.org/obo/zp//id_map_zfin.tsv) that's broken in both versions due to the double slash after `zp`. Changing it to a single slash fixes the link.

These are both upstream data quality issues. Those are what are returned from biolink. I can do "hotfixes" for both of these, but seems better to fix it at the source.

> A minor note: I like how tidy the filenames look in 3.0, but the full URL is useful to figure out, e.g., in "UCSC Bands" which filename corresponds to which gene assembly. It'd be nice if there were an option to show them on hover-over.

Added.

**Comment by vincerubinetti** [comment]
@falquaddoomi Thanks for the thorough review.

Also here is the data from 2.0 and 3.0 so you can compare side by side. This is the data at its last stage right before it is rendered. Key names not normalized.

[datasets.zip](https://github.com/monarch-initiative/monarch-ui-new/files/8051439/datasets.zip)

**Comment by vincerubinetti** [comment]
Here are normalized 2.0 vs 3.0 jsons that i'm in the process of comparing with http://www.jsondiff.com/

[noramlized-datasets.zip](https://github.com/monarch-initiative/monarch-ui-new/files/8051507/noramlized-datasets.zip)

**Comment by vincerubinetti** [comment]
@putmantime Faisal and I have reviewed this thoroughly and I'm confident it produces the same results as 2.0.

There are only a couple of questions for you:

- do we care about showing ingest date for individual files
- there are four ontologies -- `dc`, `faldo`, `foaf`, `oban`  -- [that 2.0 lists](https://github.com/monarch-initiative/monarch-ui/blob/e3e5b8ee9d22fab211bb2ba91d6ee2054a34a659/src/views/Licensing.vue#L111-L143), but are not actually part of the [obo foundry's list of ontologies](https://obofoundry.org/registry/ontologies.jsonld). can i safely remove them from 3.0 (they're currently just sitting there as blank entries)? i asked Kent about this a long time ago in slack but didn't get a clear answer.

**Review by falquaddoomi — APPROVED** [review]

**Comment by putmantime** [comment]
> * do we care about showing ingest date for individual files
No, do not worry about showing that for individual files. We were inconsistent about it previously anyway

> * there are four ontologies -- `dc`, `faldo`, `foaf`, `oban`  
These are ontologies that are likely used in the old graph but not part of OBO and won't be.
We will need to sort this out eventually, @vincerubinetti is creating an issue for manually adding them.

**Review by putmantime — APPROVED** [review]

**Pull request merged**
